# Generated by Django 3.2.4 on 2021-06-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PunchInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_in', models.TimeField()),
                ('p_out', models.TimeField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapi2.employee')),
            ],
        ),
    ]
